### PR TITLE
CollectionPage: improve icon and design and fix bugs

### LINKED ISSUE #1008: New icon for 'All categories'
what about 'A' store icon?
Screenshot 2023-02-09 at 15 25 25

_Originally posted by @anasereijo in https://github.com/ubuntu-flutter-community/software/issues/1003#issuecomment-1424370580_

### PR DESCRIPTION
**Pull request by Feichtmeier**
- fix wrong padding for expand icon in the deb updates/collection page

- new app grid icon as discussed

- new all snap category icon as discussed

- fixes to when show which button/spinner in the header

Closes #1008 
Ref #1005

### CODE REVIEW

**Comment by Feichtmeier** [comment]
needs to sort out this children chaos

**Comment by Feichtmeier** [comment]
holy hell found some horrible bugs. fixed now


https://user-images.githubusercontent.com/15329494/217943043-b9eec472-bd38-41df-b3e8-dc4bb0ad5cd3.mp4

File: lib/app/collection/package_updates_page.dart [hunk 1]
```diff
@@ -229,47 +229,43 @@ class _UpdatesListViewState extends State<_UpdatesListView> {
...
         onChange: (isExpanded) => setState(() => _isExpanded = isExpanded),
         header: MouseRegion(
           cursor: SystemMouseCursors.click,
           child: Padding(
-            padding: const EdgeInsets.only(
+            padding: EdgeInsets.only(
               top: kYaruPagePadding,
               left: kYaruPagePadding - 3,
-              bottom: kYaruPagePadding,
+              bottom: _isExpanded ? 10 : kYaruPagePadding,
```
Comment (Jupi007) [inline lib/app/collection/package_updates_page.dart:241]: This is causing the jumping effect of the expand button:

[Capture vidéo du 2023-02-09 22-46-54.webm](https://user-images.githubusercontent.com/36476595/217946621-59e8bc42-5bf0-4c61-83c0-bbb9bd4f74f0.webm)

I think you should revert it.

**Review by Jupi007 — CHANGES_REQUESTED** [review]

File: lib/app/collection/package_updates_page.dart (hunk 1 above)
Comment (Jupi007) [reply lib/app/collection/package_updates_page.dart:241]: A possible fix would be to do this:

```dart
        expandIconPadding: EdgeInsets.only(
          right: 10,
          top: _isExpanded ? kYaruPagePadding - 10 : 0,
        ),
```

But then, the expandbox height jump when you expand/shrink:

[Capture vidéo du 2023-02-09 22-53-08.webm](https://user-images.githubusercontent.com/36476595/217947892-b49398b1-24aa-4a42-8b8e-c2c4ac20a01d.webm)

Comment (Feichtmeier) [reply lib/app/collection/package_updates_page.dart]: ok the reason why I added the height jump was the big gap before the tiles

I set the padding before now to be const but added dividers instead - WDYT ?


https://user-images.githubusercontent.com/15329494/217950954-d7b74e95-d5ed-4718-9655-884281b519e3.mp4

Comment (Jupi007) [reply lib/app/collection/package_updates_page.dart]: Sorry, I can't test this in real, and I also can't zoom on my smartphone... the divider are invisible.
From that I can distinguishing it looks good, but can you post a screenshot just in case? 🙂

Comment (Feichtmeier) [reply lib/app/collection/package_updates_page.dart]: @Jupi007 

grafik
grafik

**Review by Jupi007 — APPROVED** [review]
LGFM 🚀
