### PR TITLE
fix: Installed snap list taking long to load

### LINKED ISSUE #1219: Installed snap list taking long to load
[Screencast from 2023-04-23 17-35-45.webm](https://user-images.githubusercontent.com/2129497/233849656-6429d0ba-2e6c-4bc9-bad5-4a222eba006e.webm)

### PR DESCRIPTION
**Pull request by Feichtmeier**
- let the installed snaps load as fast as possible in the UI then load the updates after
- forward the list from the service to the model, what was the reason for this unmodifyable list here @d-loose ? No critique, just curious
- make the list nullable, which gives one more state and does not leave the user with the "no snaps installed" message for some seconds while the list is loading
- to not disable the not-updates-rows while checking for updates, I see no reason why

Fixes #1219

[Bildschirmaufzeichnung vom 2023-05-30, 20-11-47.webm](https://github.com/ubuntu-flutter-community/software/assets/15329494/0701b6d6-990b-40c8-a489-779525cd2165)

### CODE REVIEW

File: lib/app/collection/snap_collection.dart [hunk 1]
```diff
@@ -115,7 +115,7 @@ class SnapCollection extends StatelessWidget {
                                 : (i == installedSnaps.length - 1
                                     ? CollectionTilePosition.bottom
                                     : CollectionTilePosition.middle)),
-                        enabled: checkingForSnapUpdates == false,
+                        enabled: true,
```
Comment (d-loose) [inline lib/app/collection/snap_collection.dart:118]: Nittiest of nitpicks: `!checkingForSnapUpdates`

Comment (Feichtmeier) [reply lib/app/collection/snap_collection.dart:118]: oh, eventually it would be better to have a second boolean getter for the time the installed apps are being looked up? 
I just set this custom widget property to always true because I thought opening and removing installed snaps should not cause any trouble when looking for updates

Comment (d-loose) [reply lib/app/collection/snap_collection.dart:118]: Ah sorry, my mind confused the added and removed lines.. I think it's fine to set it to `true` and decouple the widget from the loading state :+1:
