### PR TITLE
Use window managet set closable in a finally block

### LINKED ISSUE #110: Use window managet set closable in a finally block
Is there a danger that something could go wrong and an exception would be thrown between the `setClosable(true)` and `setClosable(false)` calls? Should `setClosable(false)` be in a [finally](https://dart.dev/guides/language/language-tour#finally) clause to avoid that one ends up stuck with a non-closable window?

_Originally posted by @jpnurmi in https://github.com/ubuntu-flutter-community/software/issues/107#issuecomment-1229221827_

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixes #110

### CODE REVIEW

File: lib/services/package_service.dart [hunk 1]
```diff
@@ -207,15 +207,17 @@ class PackageService {
...
-    setUpdatesState(UpdatesState.checkingForUpdates);
-    await _refreshCache();
-    await _getUpdates();
-    setUpdatesState(
-      _updates.isEmpty ? UpdatesState.noUpdates : UpdatesState.readyToUpdate,
-    );
-    windowManager.setClosable(true);
+    try {
+      setErrorMessage('');
+      setUpdatesState(UpdatesState.checkingForUpdates);
```
Comment (jpnurmi) [inline lib/services/package_service.dart:212]: does the window need to be non-closable when just checking for updates?

Comment (Feichtmeier) [reply lib/services/package_service.dart:212]: Yeah I think yes. Maybe it is a bit too paranoid but packagekit is not as robust as snapd from my impressions

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:
