### PR TITLE
Fix Title alignment

### LINKED ISSUE #895: Title alignment
I'm not sure what's best to have centered/aligned in relation to what but it would be nice to have a consistent alignment between pages. :)

image

### PR DESCRIPTION
**Pull request by Feichtmeier**
grafik

Fixes #895

### CODE REVIEW

File: lib/app/collection/collection_page.dart [hunk 1]
```diff
@@ -243,6 +243,7 @@ class _CollectionPageState extends State<CollectionPage> {
 
     return Scaffold(
       appBar: YaruWindowTitleBar(
+        leading: const SizedBox(width: 40),
```
Comment (jpnurmi) [inline lib/app/collection/collection_page.dart:246]: what does 40 stand for, or where does it come from?

kYaruWindowControlSize is 24, YaruTitleBarTheme.buttonPadding defaults to 10, and YaruTitleBarTheme.buttonSpacing is 14.

if the value is chosen by the eye and cannot be calculated with these, perhaps it could be shared as a constant to avoid that it gets out of sync between the files?

Comment (Feichtmeier) [reply lib/app/collection/collection_page.dart:246]: it comes from the trailing  back  buttons having a 40 pixel width

Comment (jpnurmi) [reply lib/app/collection/collection_page.dart:246]: oh wait, 40 has nothing to do with the window controls, does it? is the meaning to match the size of the back button?

Comment (jpnurmi) [reply lib/app/collection/collection_page.dart:246]: it could be nice to express that in the code so that all three places use `kBackButtonSize` or something similar from `constants.dart` because it's not immediately obvious what that 40 is :)

**Review by jpnurmi — APPROVED** [review]
